version: "3.9"
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: "demo"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "123"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  webapi:
    container_name: webapi
    build:
      context: .
      dockerfile: WebApi/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - backend

volumes:
  postgres-data:

networks:
  backend: